use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'MJCoacoa_Example' do
  pod 'MJCoacoa', :path => '../'

  target 'MJCoacoa_Tests' do
    inherit! :search_paths

    pod 'Masonry'
  end
end
